### ISSUE TITLE
module 'cyanure' has no attribute 'preprocess'

### ISSUE THREAD

**Issue by Haoqing-Wang** [facebookresearch/msn#10]
How to install the right cyanure version?

**Comment by woctezuma** [comment]
- #8

**Comment by Haoqing-Wang** [comment]
why using cyanure instead of sklearn? I find sklearn is much more faster than cyanure.

**Comment by woctezuma** [comment]
I believe the authors of `cyanure` are acquaintances of at least one of the co-authors of `MSN Masked Siamese Networks`.

Moreover, you are free to use another library if you believe you can achieve better or faster results with it.

**Comment by MidoAssran** [comment]
Hi @Haoqing-Wang, yes to the point of @woctezuma, feel free to use whatever logistic regression library you would like! Should not change the results in a significant way.
