### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by chaichaichai** [facebookresearch/msn#23]
No such file or directory: '/checkpoint/msn_os_logs/params-msn-train.yaml'
No such file or directory: '/checkpoint/msn_os_logs/msn-experiment-1_r0.csv'

**Comment by mikerabbat** [comment]
Hi, It appears you're using the `configs/pretrain/msn_vits16.yaml` config, is that correct? If so, you can either create the directory `/checkpoint/msn_os_logs` on your system, or change line 25 in the config file to point to a different directory where you want logs to be written.
