### ISSUE TITLE
Duplicate GPU detected error

### ISSUE THREAD

**Issue by amlivne** [facebookresearch/msn#24]
when running the main.py script on a local machine with 4 GPUS, I get the following error:
```Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 40```

nvidia-smi shows 4 different GPUs, and the issue persists after reboot.

**Comment by mikerabbat** [comment]
Hi, Can you please provide the exact command you are running to help with troubleshooting?

**Comment by amlivne** [comment]
`python main.py --fname configs/pretrain/msn_vits16.yaml --devices cuda:1 cuda:0`

**Comment by mikerabbat** [comment]
Hmm, that should only run on two GPUs, which shouldn't be a problem if you have 4 GPUs on your system.

Did you make any modifications to the code? Can you please provide the full output of the logs/stdout? It would help to know where this error is occurring

**Comment by amlivne** [comment]
Actually I did insert some code to support my private dataset. 
Indeed when cloning from scratch, the code works as expected without the mentioned issue, so I will close it for now. Thank you for your quick reply.
