### ISSUE TITLE
linear_eval.py #L327

### ISSUE THREAD

**Issue by Lee-YZz** [facebookresearch/msn#6]
Hi, fantastic work！Thank you for your code!
There seems to be a little omission on line 327 of 'linear_eval.py'.
[linear_eval.py #L327](https://github.com/facebookresearch/msn/blob/4388dc1eadbe3042b85d3296d41b9b207656e043/linear_eval.py#L327)
`return encoder, opt, sched, epoch, best_acc`
should be
`return encoder, linear_classifier, opt, sched, epoch, best_acc`

**Comment by MidoAssran** [comment]
Hi @Lee-YZz, thanks so much :) Will incorporate your change in the next PR!
