### ISSUE TITLE
About the 1% In1k semi-sup evaluation

### ISSUE THREAD

**Issue by merlinarer** [facebookresearch/msn#9]
Hello, thanks for your sharing,
I was littile confused about your 1% In1k semi-sup evaluation. You said in paper that the results come from logistic regression on the extracted representations. However, with the same ViT, I found this evaluation of iBoT come from end2end full fintuning(see [here](https://github.com/bytedance/ibot/tree/da316d82636a7a7356835ef224b13d5f3ace0489/evaluation)), and SwAV et. all fintuned the entire res50 encoder.

**Comment by MidoAssran** [comment]
Hi @merlinarer,

Thanks for your message. Yes, one common evaluation is end-to-end fine-tuning with 100% labels. However, with 1% labels, iBOT achieves the best performance with logistic regression on the extracted (frozen) representations.

See [Table 12 in their paper](https://arxiv.org/pdf/2111.07832.pdf) comparing fine-tuning to linear probing on 1% labels.
